// src/types/ModuleData.ts

/**
 * Defines the structure for the combined scraped data conforming to the Module schema.
 * This is a placeholder structure and should be refined based on actual scraped fields.
 */
export interface ModuleData {
  assessmentId: string;
  sourceUrl: string; // The primary URL scraped (e.g., company website)
  scrapeTimestamp: string; // ISO 8601 timestamp
  llm_ready?: boolean; // Flag indicating if data is ready for LLM processing

  company?: {
    name?: string;
    description?: string;
    aboutUs?: string;
    location?: string;
    services?: string[];
    contactInfo?: {
      email?: string;
      phone?: string;
      address?: string;
    };
    socialLinks?: {
      linkedIn?: string;
      instagram?: string;
      facebook?: string;
      twitter?: string;
      // Add other potential social platforms
    };
  };

  products?: {
    name: string;
    description?: string;
    imageUrl?: string;
    sourcePage?: string; // URL where the product was found
  }[];

  socialMediaPosts?: {
    platform: 'LinkedIn' | 'Instagram' | 'Facebook' | 'Twitter';
    postId?: string;
    url?: string;
    content?: string;
    timestamp?: string;
    author?: string;
    engagement?: {
      likes?: number;
      shares?: number;
      comments?: number;
      // Platform-specific metrics
    };
  }[];

  // Optional summary generated by backend/LLM
  summary?: {
    companyOverview?: string;
    productHighlights?: string;
    socialMediaPresence?: string;
  };

  // Raw data or other metadata if needed
  _raw?: any;
}
